version: '3.8'
services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  postgres:
    image: postgres:16-alpine
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: saralgati
      POSTGRES_PASSWORD: saralgati_dev
      POSTGRES_DB: saralgati
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  redis:
    image: redis:7-alpine
    security_opt:
      - no-new-privileges:true
    ports:
      - '6379:6379'
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
volumes:
  pgdata:
